version: "3.7"
services:
  ems-db:
    image: mysql:8.0.30
    container_name: ems-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems
    ports:
      - "33006:3306"
    volumes:
      - ./db:/var/lib/mysql